<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=iso-8859-1" />
  <title>tamgc.net - Axis &amp; Allies Naval Miniatures:  War at Sea Database</title>
  <link rel="stylesheet" type="text/css" href="./css/was.css" />
  <link rel="icon" type="image/png" href="/images/favicon.png" />
  <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" />
  <link rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-precomposed.png" />
</head>
<body>
<a class="title" href="/">
<div id="title">
  <h1 class="title">Axis &amp; Allies</h1>
  <h4 class="title">Naval Miniatures</h4>
  <h1 class="title">War at Sea</h1>
</div>
</a>

<div id="topNav">
  <a href="/">
    <div class="links">
    Home 
    </div>
  </a>
  <span class="linkDiv">|</span>
  <a href="/about.php">
    <div class="links">
    About
    </div>
  </a>
  <span class="linkDiv">|</span>
  <a href="/contact.php">
    <div class="links">
    Contact
    </div>
  </a>

  <div class="search">
  <form method="get" action="./query.php">
    <input type="text" name="query" size="20" />
    <input type="submit" value="Search" />
  </form>
  <a href="/advance.php">[Advance]</a>
  </div>
</div>
<div id="content">
